namespace WinUI.Composition.Hlsl
{
    enum HlslEffectKind { Color, Sampler, MaterializedSampler };
    enum HlslPropertyType { Scalar, Vector2, Vector3, Vector4, Matrix3x2, Matrix4x4 };
    enum HlslShaderProfile { Level91, Level93, Pixel40 };
    enum HlslNativeArchitecture { Unknown, X86, X64, Arm64 };
    enum HlslRuntimeSupportLevel { Unsupported, Experimental, Validated };
    [default_interface] runtimeclass HlslRuntimeCapabilities
    {
        HlslNativeArchitecture Architecture{ get; };
        HlslRuntimeSupportLevel SupportLevel{ get; };
        Boolean NativeAdapterAvailable{ get; };
        Boolean SupportsCompositionGraphNodes{ get; };
        Boolean SupportsMaterializedGraphs{ get; };
        Boolean SupportsAsyncCompilation{ get; };
        Boolean UsesPrivateCompositionAbi{ get; };
    }
    [default_interface] runtimeclass HlslShaderLibrary
    {
        static HlslShaderLibrary Create(Windows.Storage.Streams.IBuffer bytecode, HlslShaderProfile profile);
        static HlslShaderLibrary CreateFromByteArray(UInt8[] bytecode, HlslShaderProfile profile);
        static HlslShaderLibrary CreateFromGeneratedByteArray(UInt8[] bytecode);
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> LoadFromFileAsync(Windows.Storage.StorageFile file, HlslShaderProfile profile);
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> LoadFromApplicationUriAsync(Windows.Foundation.Uri uri, HlslShaderProfile profile);
        HlslShaderProfile Profile{ get; };
        HlslEffectKind EffectKind{ get; };
        Windows.Storage.Streams.IBuffer Bytecode{ get; };
    }
    [default_interface] runtimeclass HlslFloatProperty
    {
        HlslFloatProperty(String name, Single defaultValue, Single minimum, Single maximum);
        String Name{ get; };
        Single DefaultValue{ get; };
        Single Minimum{ get; };
        Single Maximum{ get; };
    }
    [default_interface] runtimeclass HlslProperty
    {
        HlslProperty(String name, HlslPropertyType type, Windows.Foundation.Collections.IVectorView<Single> defaultValue);
        String Name{ get; };
        HlslPropertyType Type{ get; };
        Windows.Foundation.Collections.IVectorView<Single> DefaultValue{ get; };
    }
    runtimeclass HlslCompiler
    {
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> CompileAsync(String shader, HlslEffectKind kind, HlslShaderProfile profile);
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> CompileWithDefinesAsync(String shader, HlslEffectKind kind, HlslShaderProfile profile, Windows.Foundation.Collections.IVectorView<String> defines);
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> CompileWithPropertiesAsync(String shader, HlslEffectKind kind, HlslShaderProfile profile, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static Windows.Foundation.IAsyncOperation<HlslShaderLibrary> CompileWithPropertiesAndDefinesAsync(String shader, HlslEffectKind kind, HlslShaderProfile profile, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties, Windows.Foundation.Collections.IVectorView<String> defines);
    }
    runtimeclass HlslEffect;
    runtimeclass HlslEffectFactory;
    runtimeclass HlslEffectBrush;
    [default_interface] runtimeclass HlslEffect
    {
        static HlslEffect CreateColor(Guid id, String shader);
        static HlslEffect CreateSampler(Guid id, String shader);
        static HlslEffect CreateMaterializedSampler(Guid id, String shader);
        static HlslEffect CreateColorTransform(String shader);
        static HlslEffect CreateCustomSampler(String shader);
        static HlslEffect CreateCustomMaterializedSampler(String shader);
        static HlslEffect CreateCompiled(Guid id, HlslShaderLibrary shader);
        static HlslEffect CreateCompiledFromGeneratedByteArray(Guid id, UInt8[] bytecode);
        static HlslEffect CreateCompiledColor(Guid id, HlslShaderLibrary shader);
        static HlslEffect CreateCompiledSampler(Guid id, HlslShaderLibrary shader);
        static HlslEffect CreateCompiledMaterializedSampler(Guid id, HlslShaderLibrary shader);
        static HlslEffect CreateColorWithProperties(String shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateSamplerWithProperties(String shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateMaterializedSamplerWithProperties(String shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateCompiledColorWithProperties(Guid id, HlslShaderLibrary shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateCompiledSamplerWithProperties(Guid id, HlslShaderLibrary shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateCompiledMaterializedSamplerWithProperties(Guid id, HlslShaderLibrary shader, String sourceName, Windows.Foundation.Collections.IVectorView<HlslFloatProperty> properties);
        static HlslEffect CreateAdvanced(String shader, HlslEffectKind kind, Windows.Foundation.Collections.IVectorView<String> sourceNames, Windows.Foundation.Collections.IVectorView<HlslProperty> properties);
        static HlslEffect CreateCompiledAdvanced(Guid id, HlslShaderLibrary shader, HlslEffectKind kind, Windows.Foundation.Collections.IVectorView<String> sourceNames, Windows.Foundation.Collections.IVectorView<HlslProperty> properties);
        Guid Id{ get; };
        HlslEffectKind Kind{ get; };
        String SourceName{ get; };
        Windows.Foundation.Collections.IVectorView<String> SourceNames{ get; };
        Boolean IsPrecompiled{ get; };
        Windows.Foundation.Collections.IVectorView<String> PropertyNames{ get; };
        String GetPropertyPath(String name);
        Windows.Foundation.Collections.IVectorView<String> GetAnimatablePropertyPaths();
        Windows.Graphics.Effects.IGraphicsEffect CreateGraphicsEffect();
        Windows.Graphics.Effects.IGraphicsEffect CreateGraphicsEffectWithSource(Windows.Graphics.Effects.IGraphicsEffectSource source);
        Windows.Graphics.Effects.IGraphicsEffect CreateGraphicsEffectWithSources(Windows.Foundation.Collections.IVectorView<Windows.Graphics.Effects.IGraphicsEffectSource> sources);
    }
    [default_interface] runtimeclass HlslEffectFactory
    {
        Microsoft.UI.Composition.CompositionEffectFactory Factory{ get; };
        HlslEffectBrush CreateBrush();
    }
    [default_interface] runtimeclass HlslEffectBrush
    {
        Microsoft.UI.Composition.CompositionBrush Brush{ get; };
        Microsoft.UI.Composition.CompositionEffectBrush EffectBrush{ get; };
        Microsoft.UI.Composition.CompositionPropertySet Properties{ get; };
        String GetPropertyPath(String name);
        void SetSource(String name, Microsoft.UI.Composition.CompositionBrush source);
        void SetFloat(String name, Single value);
        void SetVector2(String name, Windows.Foundation.Numerics.Vector2 value);
        void SetVector3(String name, Windows.Foundation.Numerics.Vector3 value);
        void SetVector4(String name, Windows.Foundation.Numerics.Vector4 value);
        void SetMatrix3x2(String name, Windows.Foundation.Numerics.Matrix3x2 value);
        void SetMatrix4x4(String name, Windows.Foundation.Numerics.Matrix4x4 value);
    }
    runtimeclass HlslComposition
    {
        static HlslRuntimeCapabilities GetRuntimeCapabilities();
        static HlslEffectFactory CreateEffectFactory(Microsoft.UI.Composition.Compositor compositor, HlslEffect effect);
        static HlslEffectBrush CreateBackdropBrush(Microsoft.UI.Composition.Compositor compositor, HlslEffect effect);
        static Microsoft.UI.Xaml.Media.Brush CreateXamlBrush(HlslEffectBrush brush);
        static Microsoft.UI.Xaml.Media.Brush CreateXamlBrushFromCompositionBrush(Microsoft.UI.Composition.CompositionBrush brush);
    }
    [default_interface] runtimeclass LiquidGlassMaterial
    {
        LiquidGlassMaterial(Microsoft.UI.Composition.Compositor compositor);
        HlslEffectBrush EffectBrush{ get; };
        Single BlurRadius;
        Single RefractionStrength;
        Single DispersionStrength;
        Single CornerRadius;
        Single BorderThickness;
        Single HighlightStrength;
    }
    [default_interface] runtimeclass LiquidGlassBrush : Microsoft.UI.Xaml.Media.XamlCompositionBrushBase
    {
        LiquidGlassBrush();
        Boolean IsEnabled;
        static Microsoft.UI.Xaml.DependencyProperty IsEnabledProperty{ get; };
        Double BlurRadius;
        static Microsoft.UI.Xaml.DependencyProperty BlurRadiusProperty{ get; };
        Double RefractionStrength;
        static Microsoft.UI.Xaml.DependencyProperty RefractionStrengthProperty{ get; };
        Double DispersionStrength;
        static Microsoft.UI.Xaml.DependencyProperty DispersionStrengthProperty{ get; };
        Double CornerRadius;
        static Microsoft.UI.Xaml.DependencyProperty CornerRadiusProperty{ get; };
        Double BorderThickness;
        static Microsoft.UI.Xaml.DependencyProperty BorderThicknessProperty{ get; };
        Double HighlightStrength;
        static Microsoft.UI.Xaml.DependencyProperty HighlightStrengthProperty{ get; };
    }
}
