#pragma once
import winrt.Microsoft.UI.Composition;
import winrt.Microsoft.UI.Xaml.Media;
import winrt.Windows.Graphics.Effects;
import std;
namespace hlsl::engine
{
	// HLSL contract: export float4 PSBody(float4 color).
	// Input/output colors are premultiplied. Registration owns the source for process lifetime.
	// Reusing a GUID with different code is rejected.
	winrt::Windows::Graphics::Effects::IGraphicsEffect CreateColorEffect(winrt::guid const& id, std::string_view hlsl);

	// HLSL contract: float4 Shade(float2 uv, float4 samplerDataExt).
	// texture0/sampler0 and edge-mode exports are generated by this API.
	winrt::Windows::Graphics::Effects::IGraphicsEffect CreateSamplerEffect(winrt::guid const& id, std::string_view hlsl);

	// The result remains a normal CompositionEffectBrush (sources and properties are animatable).
	winrt::Microsoft::UI::Composition::CompositionEffectBrush CreateBackdropBrush(winrt::Microsoft::UI::Composition::Compositor const& compositor, winrt::Windows::Graphics::Effects::IGraphicsEffect const& effect);

	winrt::Microsoft::UI::Xaml::Media::XamlCompositionBrushBase AsXamlBrush(winrt::Microsoft::UI::Composition::CompositionBrush const& brush);

	// Advanced sampler effects and animatable constants use the CustomEffectRuntime module descriptors.
	// The adapter is deliberately version-bounded: Windows App SDK 2.4.0 x64.
}

