<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<UseWinUI>true</UseWinUI>
		<Platforms>x64;ARM64;x86</Platforms>
		<AssetTargetFallback>$(AssetTargetFallback);native</AssetTargetFallback>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyName>WinUI.Composition.Hlsl.Projection</AssemblyName>
		<CsWinRTIncludes>WinUI.Composition.Hlsl</CsWinRTIncludes>
		<CsWinRTGeneratedFilesDir>$(BaseIntermediateOutputPath)$(Configuration)\$(Platform)\Generated\</CsWinRTGeneratedFilesDir>
		<IsPackable>true</IsPackable>
		<NuspecFile>../packaging/WinUI.Composition.Hlsl.nuspec</NuspecFile>
		<NuspecBasePath>$(MSBuildThisFileDirectory)..</NuspecBasePath>
		<PackageOutputPath>../artifacts/packages</PackageOutputPath>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Generated/**/*.cs"/>
		<PackageReference Include="Microsoft.Windows.CsWinRT" PrivateAssets="all"/>
		<PackageReference Include="Microsoft.WindowsAppSDK"/>
		<ProjectReference Include="../src/WinUI.Composition.Hlsl/WinUI.Composition.Hlsl.vcxproj"/>
	</ItemGroup>
	<Target Name="BuildNativeRuntimesForPack" BeforeTargets="Pack">
		<MSBuild
		  Projects="../src/WinUI.Composition.Hlsl/WinUI.Composition.Hlsl.vcxproj"
		  Targets="Build"
		  BuildInParallel="false"
		  Properties="Configuration=Release;Platform=x64"/>
		<MSBuild
		  Projects="../src/WinUI.Composition.Hlsl/WinUI.Composition.Hlsl.vcxproj"
		  Targets="Build"
		  BuildInParallel="false"
		  Properties="Configuration=Release;Platform=Win32"/>
		<MSBuild
		  Projects="../src/WinUI.Composition.Hlsl/WinUI.Composition.Hlsl.vcxproj"
		  Targets="Build"
		  BuildInParallel="false"
		  Properties="Configuration=Release;Platform=ARM64"/>
	</Target>
</Project>
