<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<HlslNativeArchitecture Condition="'$(Platform)'=='Win32'">x86</HlslNativeArchitecture>
		<HlslNativeArchitecture Condition="'$(HlslNativeArchitecture)'==''">$(Platform)</HlslNativeArchitecture>
		<HlslWinmd Condition="'$(HlslWinmd)'==''">$(MSBuildThisFileDirectory)..\..\lib\native\WinUI.Composition.Hlsl.winmd</HlslWinmd>
		<HlslNativeDll Condition="'$(HlslNativeDll)'==''">$(MSBuildThisFileDirectory)..\..\runtimes\win-$(HlslNativeArchitecture)\native\WinUI.Composition.Hlsl.dll</HlslNativeDll>
		<HlslCompositionIntermediateRoot Condition="'$(HlslCompositionIntermediateRoot)'==''">$(IntDir)Hlsl\</HlslCompositionIntermediateRoot>
		<HlslCompositionOutputRoot Condition="'$(HlslCompositionOutputRoot)'==''">$(OutDir)Hlsl\</HlslCompositionOutputRoot>
		<HlslCompositionGenerateHeaders Condition="'$(HlslCompositionGenerateHeaders)'==''">true</HlslCompositionGenerateHeaders>
		<HlslCompositionPublishAsContent Condition="'$(HlslCompositionPublishAsContent)'==''">true</HlslCompositionPublishAsContent>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="$(HlslWinmd)">
			<Implementation>WinUI.Composition.Hlsl.dll</Implementation>
		</Reference>
		<ReferenceCopyLocalPaths Include="$(HlslNativeDll)"/>
	</ItemGroup>
	<Target Name="HlslConfigureGeneratedShaderIncludes" BeforeTargets="ClCompile" Condition="'@(HlslCompositionShader)'!='' and '$(HlslCompositionGenerateHeaders)'=='true'">
		<ItemGroup>
			<ClCompile Update="@(ClCompile)">
				<AdditionalIncludeDirectories>$(HlslCompositionIntermediateRoot);%(ClCompile.AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
			</ClCompile>
		</ItemGroup>
	</Target>
	<Target Name="HlslRegisterNativeShaderContent"
			BeforeTargets="PrepareForBuild"
			Condition="'$(HlslCompositionPublishAsContent)'=='true' and '@(HlslCompositionShader)'!=''">
		<ItemGroup>
			<Content Include="%(_HlslCompositionTracked.TrackedDxbc)">
				<Link>Hlsl\%(_HlslCompositionTracked.AssetRelativePath)</Link>
				<TargetPath>Hlsl\%(_HlslCompositionTracked.AssetRelativePath)</TargetPath>
				<DeploymentContent>true</DeploymentContent>
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			</Content>
		</ItemGroup>
	</Target>
	<Target Name="HlslCheckNativeAsset" BeforeTargets="PrepareForBuild" Condition="!Exists('$(HlslNativeDll)')">
		<Error Text="This WinUI.Composition.Hlsl package does not contain a native binary for $(HlslNativeArchitecture)."/>
	</Target>
	<Import Project="$(MSBuildThisFileDirectory)WinUI.Composition.Hlsl.Build.targets" />
</Project>
