namespace WinUI.Composition.Hlsl.Controls
{
    [webhosthidden] runtimeclass LiquidGlassButton : Microsoft.UI.Xaml.Controls.Button
    {
        LiquidGlassButton();
        WinUI.Composition.Hlsl.LiquidGlassBrush GlassBrush{ get; };
    }

    [webhosthidden] runtimeclass LiquidGlassToggleButton : Microsoft.UI.Xaml.Controls.Primitives.ToggleButton
    {
        LiquidGlassToggleButton();
        WinUI.Composition.Hlsl.LiquidGlassBrush GlassBrush{ get; };
    }

    [webhosthidden] runtimeclass LiquidGlassCard : Microsoft.UI.Xaml.Controls.ContentControl
    {
        LiquidGlassCard();
        WinUI.Composition.Hlsl.LiquidGlassBrush GlassBrush{ get; };
    }

    [webhosthidden] runtimeclass LiquidGlassSlider : Microsoft.UI.Xaml.Controls.Slider
    {
        LiquidGlassSlider();
        WinUI.Composition.Hlsl.LiquidGlassBrush GlassBrush{ get; };
    }
}
